BASE_PATH=${HOME}/ocm-hosted-clusters
AWS_CREDS="${HOME}/.aws/credentials"

# For public clusters, just use "oc"
OC="oc --backplane-as-cluster-admin"

CONTROL_PLANE_AVAILABILITY_POLICY="HighlyAvailable"

# SVC Context
SVC_REGION=""
SVC_CLUSTER_NAME=""
SVC_CLUSTER_DIR="${BASE_PATH}/${SVC_CLUSTER_NAME}"
SVC_KUBECONFIG="${SVC_CLUSTER_DIR}/kubeconfig"

# SVC2 Context
SVC2_REGION=""
SVC2_CLUSTER_NAME=""
SVC2_CLUSTER_DIR="${BASE_PATH}/${SVC2_CLUSTER_NAME}"
SVC2_KUBECONFIG="${SVC2_CLUSTER_DIR}/kubeconfig"

# MGMT Context
MGMT_REGION=""
MGMT_CLUSTER_NAME=""
MGMT_CLUSTER_DIR="${BASE_PATH}/${MGMT_CLUSTER_NAME}"
MGMT_KUBECONFIG="${MGMT_CLUSTER_DIR}/kubeconfig"

# MGMT2 Context
MGMT2_REGION=""
MGMT2_CLUSTER_NAME=""
MGMT2_CLUSTER_DIR="${BASE_PATH}/${MGMT2_CLUSTER_NAME}"
MGMT2_KUBECONFIG="${MGMT2_CLUSTER_DIR}/kubeconfig"

# Hosted Cluster Context
HC_CLUSTER_NS=""
HC_ENV=""
HC_REGION=""

# S3 ETCD Backups
BUCKET_NAME=""
