SSH_KEY_FILE=${HOME}/.ssh/id_rsa.pub
BASE_PATH=${HOME}/Documents/ocp/ocm-hosted-clusters
PULL_SECRET_FILE="${HOME}/Documents/ocp/pull_secret.json"
AWS_CREDS="${HOME}/Documents/ocp/credentials"

CONTROL_PLANE_AVAILABILITY_POLICY="HighlyAvailable"
HYPERSHIFT_PATH=${HOME}
HYPERSHIFT_CLI=${HYPERSHIFT_PATH}/bin/hypershift
HYPERSHIFT_IMAGE=${HYPERSHIFT_IMAGE:-"quay.io/hypershift/hypershift:latest"}
NODE_POOL_REPLICAS=${NODE_POOL_REPLICAS:-2}

# SVC Context
SVC_REGION=us-west-2
SVC_CLUSTER_NAME=""
SVC_CLUSTER_DIR="${BASE_PATH}/${SVC_CLUSTER_NAME}"
SVC_KUBECONFIG="${SVC_CLUSTER_DIR}/kubeconfig"

# SVC2 Context
SVC2_REGION=us-west-2
SVC2_CLUSTER_NAME=""
SVC2_CLUSTER_DIR="${BASE_PATH}/${SVC2_CLUSTER_NAME}"
SVC2_KUBECONFIG="${SVC2_CLUSTER_DIR}/kubeconfig"

# MGMT Context
MGMT_REGION=us-west-2
MGMT_CLUSTER_NAME=""
MGMT_CLUSTER_DIR="${BASE_PATH}/${MGMT_CLUSTER_NAME}"
MGMT_KUBECONFIG="${MGMT_CLUSTER_DIR}/kubeconfig"

# MGMT2 Context
MGMT2_REGION=us-west-2
MGMT2_CLUSTER_NAME=""
MGMT2_CLUSTER_DIR="${BASE_PATH}/${MGMT2_CLUSTER_NAME}"
MGMT2_KUBECONFIG="${MGMT2_CLUSTER_DIR}/kubeconfig"

# Hosted Cluster Context
HC_CLUSTER_ID=
HC_CLUSTER_NS=${HC_CLUSTER_ID}
HC_REGION=us-west-2
HC_CLUSTER_NAME=""
HC_CLUSTER_DIR="${BASE_PATH}/${HC_CLUSTER_NAME}"
HC_KUBECONFIG="${HC_CLUSTER_DIR}/kubeconfig"
BACKUP_DIR=${HC_CLUSTER_DIR}/backup

# S3 ETCD Backups
BUCKET_NAME="somes3bucket"

# DNS
AWS_ZONE_ID=""
EXTERNAL_DNS_DOMAIN=""